PATH = './out'
PATH_FIGS = PATH+'/figs_graphs'
PATH_GRAPHS = PATH+'/out_graphs'
PATH_MATRICES = PATH+'/out_matrices' 

TRACKER = 'TRACKER'
MONITOR = 'MONITOR'
PEER = 'PEER'
MASTERSERVER = 'MASTER SERVER'

COLOR_TRACKER = 'red'
COLOR_MONITOR = 'blue'
COLOR_PEER = 'green'
COLOR_MASTERSERVER = 'yellow'

SHOWMASTER = None
SHOWPEERS = None